In [2]:


import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
df_number_csv = pd.DataFrame({'number': [101, 102, 103, 104, 105, 106, 107, 108, 109, 111, 112, 113, 114 , 115, 116, 117, 118, 119, 121, 122, 123 , 124, 200, 201, 202, 203, 205, 207, 208, 209, 210, 212, 213, 214, 215,  217, 219, 220, 221, 222, 223, 228, 230, 231, 232, 233, 234]})
df_number_csv

In [20]:
# Работаем с первым столбцом
df_number_csv = pd.DataFrame({'number': [104, 105, 106, 107, 108, 109, 111, 112, 113, 114 , 115, 116, 117, 118, 119, 121, 122, 123 , 124, 200, 201, 202, 203, 205, 207, 208, 209, 210, 212, 213, 214, 215,  217, 219, 220, 221, 222, 223, 228, 230, 231, 232, 233, 234]})
df_number_csv

for i in range (len(df_number_csv)):


    number = df_number_csv.iloc[i]['number']

    path_annotations = f"data\{number}annotations.txt"
    df_annotations = pd.read_table(path_annotations, sep='\s+', engine='python')

    path_data = f"data\{number}.csv"
    df_data = pd.read_csv(path_data, sep=",")

    if df_data.columns[1] == "'MLII'":

        # удаляем столбец
        df_data.drop (columns=df_data.columns [2], axis= 1 , inplace= True )

        df_data['Type'] = np.nan
        df_data['heart_beat'] = np.nan

        last_sample = 0
        
        for i in range(len(df_annotations)):

            if i < 2:
                for g in range(last_sample, df_annotations.iloc[i]['Sample#']):
                    df_data.loc[g,'Type'] = df_annotations.iloc[i]['Type']
                    df_data.loc[g,'heart_beat'] = i
            
            else:

                j = i -1
                for g in range(last_sample, df_annotations.iloc[i]['Sample#']):
                    df_data.loc[g,'Type'] = df_annotations.iloc[j]['Type']
                    df_data.loc[g,'heart_beat'] = i

            last_sample = df_annotations.iloc[i]['Sample#']
            last_type = df_annotations.iloc[i]['Type']

        for i in range(last_sample, len(df_data)):
            df_data.loc[i,'Type'] = last_type
            df_data.loc[i,'heart_beat'] = df_data.loc[last_sample-1,'heart_beat']+1

        path_save = f"data\MLII\{number}MLII.csv"
        df_data.to_csv(path_save, sep=',', index=False)

    if df_data.columns[1] == "'V5'":

        # удаляем столбец
        df_data.drop (columns=df_data.columns [2], axis= 1 , inplace= True )

        df_data['Type'] = np.nan
        df_data['heart_beat'] = np.nan

        last_sample = 0
        
        for i in range(len(df_annotations)):

            if i < 2:
                for g in range(last_sample, df_annotations.iloc[i]['Sample#']):
                    df_data.loc[g,'Type'] = df_annotations.iloc[i]['Type']
                    df_data.loc[g,'heart_beat'] = i
            
            else:

                j = i -1
                for g in range(last_sample, df_annotations.iloc[i]['Sample#']):
                    df_data.loc[g,'Type'] = df_annotations.iloc[j]['Type']
                    df_data.loc[g,'heart_beat'] = i

            last_sample = df_annotations.iloc[i]['Sample#']
            last_type = df_annotations.iloc[i]['Type']

        for i in range(last_sample, len(df_data)):
            df_data.loc[i,'Type'] = last_type
            df_data.loc[i,'heart_beat'] = df_data.loc[last_sample-1,'heart_beat']+1

        path_save = f"data\V5\{number}V5.csv"
        df_data.to_csv(path_save, sep=',', index=False)

In [8]:
# Работаем со вторым столбцом
df_number_csv = pd.DataFrame({'number': [103, 104, 105, 106, 107, 108, 109, 111, 112, 113, 114 , 115, 116, 117, 118, 119, 121, 122, 123 , 124, 200, 201, 202, 203, 205, 207, 208, 209, 210, 212, 213, 214, 215,  217, 219, 220, 221, 222, 223, 228, 230, 231, 232, 233, 234]})
df_number_csv

for i in range (len(df_number_csv)):


    number = df_number_csv.iloc[i]['number']

    path_annotations = f"data\{number}annotations.txt"
    df_annotations = pd.read_table(path_annotations, sep='\s+', engine='python')

    path_data = f"data\{number}.csv"
    df_data = pd.read_csv(path_data, sep=",")

    if df_data.columns[2] == "'V1'":

        # удаляем столбец
        df_data.drop (columns=df_data.columns [1], axis= 1 , inplace= True )

        df_data['Type'] = np.nan
        df_data['heart_beat'] = np.nan

        last_sample = 0
        
        for i in range(len(df_annotations)):

            if i < 2:
                for g in range(last_sample, df_annotations.iloc[i]['Sample#']):
                    df_data.loc[g,'Type'] = df_annotations.iloc[i]['Type']
                    df_data.loc[g,'heart_beat'] = i
            
            else:

                j = i -1
                for g in range(last_sample, df_annotations.iloc[i]['Sample#']):
                    df_data.loc[g,'Type'] = df_annotations.iloc[j]['Type']
                    df_data.loc[g,'heart_beat'] = i

            last_sample = df_annotations.iloc[i]['Sample#']
            last_type = df_annotations.iloc[i]['Type']

        for i in range(last_sample, len(df_data)):
            df_data.loc[i,'Type'] = last_type
            df_data.loc[i,'heart_beat'] = df_data.loc[last_sample-1,'heart_beat']+1

        path_save = f"data\V1\{number}V1.csv"
        df_data.to_csv(path_save, sep=',', index=False)

    if df_data.columns[2] == "'V2'":

        # удаляем столбец
        df_data.drop (columns=df_data.columns [1], axis= 1 , inplace= True )

        df_data['Type'] = np.nan
        df_data['heart_beat'] = np.nan

        last_sample = 0
        
        for i in range(len(df_annotations)):

            if i < 2:
                for g in range(last_sample, df_annotations.iloc[i]['Sample#']):
                    df_data.loc[g,'Type'] = df_annotations.iloc[i]['Type']
                    df_data.loc[g,'heart_beat'] = i
            
            else:

                j = i -1
                for g in range(last_sample, df_annotations.iloc[i]['Sample#']):
                    df_data.loc[g,'Type'] = df_annotations.iloc[j]['Type']
                    df_data.loc[g,'heart_beat'] = i

            last_sample = df_annotations.iloc[i]['Sample#']
            last_type = df_annotations.iloc[i]['Type']

        for i in range(last_sample, len(df_data)):
            df_data.loc[i,'Type'] = last_type
            df_data.loc[i,'heart_beat'] = df_data.loc[last_sample-1,'heart_beat']+1

        path_save = f"data\V2\{number}V2.csv"
        df_data.to_csv(path_save, sep=',', index=False)


    if df_data.columns[2] == "'V4'":

        # удаляем столбец
        df_data.drop (columns=df_data.columns [1], axis= 1 , inplace= True )

        df_data['Type'] = np.nan
        df_data['heart_beat'] = np.nan

        last_sample = 0
        
        for i in range(len(df_annotations)):

            if i < 2:
                for g in range(last_sample, df_annotations.iloc[i]['Sample#']):
                    df_data.loc[g,'Type'] = df_annotations.iloc[i]['Type']
                    df_data.loc[g,'heart_beat'] = i
            
            else:

                j = i -1
                for g in range(last_sample, df_annotations.iloc[i]['Sample#']):
                    df_data.loc[g,'Type'] = df_annotations.iloc[j]['Type']
                    df_data.loc[g,'heart_beat'] = i

            last_sample = df_annotations.iloc[i]['Sample#']
            last_type = df_annotations.iloc[i]['Type']

        for i in range(last_sample, len(df_data)):
            df_data.loc[i,'Type'] = last_type
            df_data.loc[i,'heart_beat'] = df_data.loc[last_sample-1,'heart_beat']+1

        path_save = f"data\V4\{number}V4.csv"
        df_data.to_csv(path_save, sep=',', index=False)


    if df_data.columns[2] == "'V5'":

        # удаляем столбец
        df_data.drop (columns=df_data.columns [1], axis= 1 , inplace= True )

        df_data['Type'] = np.nan
        df_data['heart_beat'] = np.nan

        last_sample = 0
        
        for i in range(len(df_annotations)):

            if i < 2:
                for g in range(last_sample, df_annotations.iloc[i]['Sample#']):
                    df_data.loc[g,'Type'] = df_annotations.iloc[i]['Type']
                    df_data.loc[g,'heart_beat'] = i
            
            else:

                j = i -1
                for g in range(last_sample, df_annotations.iloc[i]['Sample#']):
                    df_data.loc[g,'Type'] = df_annotations.iloc[j]['Type']
                    df_data.loc[g,'heart_beat'] = i

            last_sample = df_annotations.iloc[i]['Sample#']
            last_type = df_annotations.iloc[i]['Type']

        for i in range(last_sample, len(df_data)):
            df_data.loc[i,'Type'] = last_type
            df_data.loc[i,'heart_beat'] = df_data.loc[last_sample-1,'heart_beat']+1

        path_save = f"data\V5\{number}V5.csv"
        df_data.to_csv(path_save, sep=',', index=False)

In [5]:
df_number_csv = pd.DataFrame({'number': [100, 101, 103, 105, 108, 112, 113, 115, 116, 117, 121, 122, 123, 201, 202, 203, 205, 209, 210, 213, 215, 219, 220, 222, 223, 228, 230, 234]})
df_number_csv

    number
0      100
1      101
2      103
3      105
4      108
5      112
6      113
7      115
8      116
9      117
10     121
11     122
12     123
13     201
14     202
15     203
16     205
17     209
18     210
19     213
20     215
21     219
22     220
23     222
24     223
25     228
26     230
27     234

In [9]:
# Выделяем целые удары сердца
for i in range (len(df_number_csv)):


    number = df_number_csv.iloc[i]['number']

    path_data = f"data\MLII\{number}MLII.csv"
    df_data = pd.read_csv(path_data, sep=",")

    last_heart_beat = df_data.loc[len(df_data)-1,'heart_beat']
    df_data = df_data[(df_data.heart_beat != 0)&(df_data.heart_beat != 1)&(df_data.heart_beat != last_heart_beat)]
    df_data.heart_beat -= 1
    

    path_save = f"data\MLII(whole_beats)\{number}MLII.csv"
    df_data.to_csv(path_save, sep=',', index=False)

In [14]:
# Склеиваем по 15 ударов с каждой ЭКГ удаляя неправильные удары 

for i in range (len(df_number_csv)):


    number = df_number_csv.iloc[i]['number']

    path_data = f"data\MLII(whole_beats)\{number}MLII.csv"
    df_data = pd.read_csv(path_data, sep=",")
    if i == 0:
        df_data_all = df_data[(df_data.heart_beat < 16)]
    else:
        df_data = df_data[(df_data.heart_beat < 16)]
        df_data_all = pd.concat([df_data_all, df_data], ignore_index=True)
    
df_data_all = df_data_all[(df_data_all.Type == 'N')]

display(df_data_all)

path_save = f"data\DataTrain\TrainMLII(NS).csv"
df_data_all.to_csv(path_save, sep=',', index=False)

        'sample #'  'MLII' Type  heart_beat
0               77    1192    N         1.0
1               78    1177    N         1.0
2               79    1128    N         1.0
3               80    1058    N         1.0
4               81     991    N         1.0
...            ...     ...  ...         ...
121513        3699    1110    N        15.0
121514        3700    1161    N        15.0
121515        3701    1212    N        15.0
121516        3702    1258    N        15.0
121517        3703    1295    N        15.0

[119959 rows x 4 columns]

In [17]:
# Не знаю надо ли, но проставляю номер сэмпла с 0 и номера ударов
df_data = pd.read_csv(r'data\DataTrain\TrainMLII(NS).csv', sep=",")
for i in range (len(df_data)):
    if i==0:

        heart_beat = df_data.loc[i,'heart_beat']
        count = 1
        df_data.loc[i,'\'sample #\''] = i
        
    else:

        heart_beat = df_data.loc[i,'heart_beat']

        if heart_beat != last_heart_beat:
            count = count + 1
        
        df_data.loc[i,'\'sample #\''] = i

    last_heart_beat = df_data.loc[i,'heart_beat']
    df_data.loc[i,'heart_beat'] = count
    
display(df_data)

path_save = f"data\DataTrain\TrainMLII.csv"
df_data.to_csv(path_save, sep=',', index=False)

        'sample #'  'MLII' Type  heart_beat
0                0    1192    N         1.0
1                1    1177    N         1.0
2                2    1128    N         1.0
3                3    1058    N         1.0
4                4     991    N         1.0
...            ...     ...  ...         ...
119954      119954    1110    N       412.0
119955      119955    1161    N       412.0
119956      119956    1212    N       412.0
119957      119957    1258    N       412.0
119958      119958    1295    N       412.0

[119959 rows x 4 columns]